# Generated by Django 5.2.6 on 2025-09-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('geojson', models.FileField(upload_to='aoi/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
