# Generated by Django 5.2.6 on 2025-09-26 12:07

import app_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=app_core.models.avatar_upload_to),
        ),
    ]
