# Generated by Django 5.2.6 on 2025-09-27 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_delete_aoi_remove_profile_bio_remove_profile_phone_and_more'),
    ]

    operations = [
    ]
