# Generated by Django 5.2.6 on 2025-09-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0013_alter_profile_main_crop_alter_profile_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, help_text='Primary contact number', max_length=20),
        ),
    ]
