# Generated by Django 5.2.6 on 2025-09-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0010_add_fullname_dob_to_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('banteay_meanchey', 'Banteay Meanchey'), ('battambang', 'Battambang'), ('kampong_cham', 'Kampong Cham'), ('kampong_chhnang', 'Kampong Chhnang'), ('kampong_speu', 'Kampong Speu'), ('kampong_thom', 'Kampong Thom'), ('kampot', 'Kampot'), ('kandal', 'Kandal'), ('koh_kong', 'Koh Kong'), ('kratie', 'Kratie'), ('mondulkiri', 'Mondulkiri'), ('phnom_penh', 'Phnom Penh'), ('preah_vihear', 'Preah Vihear'), ('prey_veng', 'Prey Veng'), ('pursat', 'Pursat'), ('ratanakiri', 'Ratanakiri'), ('siem_reap', 'Siem Reap'), ('preah_sihanouk', 'Preah Sihanouk'), ('stueng_treng', 'Stung Treng'), ('svay_rieng', 'Svay Rieng'), ('takeo', 'Takeo'), ('oddar_meanchey', 'Oddar Meanchey'), ('kep', 'Kep'), ('pailin', 'Pailin'), ('tboung_khmum', 'Tbong Khmum')], default='unspecified', max_length=64),
        ),
    ]
