# Generated by Django 5.2.6 on 2025-09-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0003_analysisjob_overlay_html_analysisjob_overlay_png'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='hotspots_geojson',
            field=models.FileField(blank=True, null=True, upload_to='hotspots/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='overlay_html',
            field=models.FileField(blank=True, null=True, upload_to='overlays/'),
        ),
        migrations.AlterField(
            model_name='analysisjob',
            name='overlay_png',
            field=models.ImageField(blank=True, null=True, upload_to='overlays/'),
        ),
    ]
