# Generated by Django 5.2.6 on 2025-09-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_fieldaoi_analysisjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisjob',
            name='overlay_html',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='analysisjob',
            name='overlay_png',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
