# Generated by Django 5.2.6 on 2025-09-27 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0009_fill_main_crop_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_crop',
            field=models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('sen_kraop', 'Sen Kra’op'), ('phka_rumduol', 'Phka Rumduol'), ('ir50404', 'IR50404'), ('om5451', 'OM5451'), ('other', 'Other')], default='unspecified', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='province',
            field=models.CharField(blank=True, choices=[('unspecified', 'Unspecified'), ('phnom_penh', 'Phnom Penh'), ('kandal', 'Kandal'), ('kampong_cham', 'Kampong Cham')], default='unspecified', max_length=64),
        ),
    ]
